name: VulnBot Action
on:
  push:
    branches: ["main"]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Send report
        # Using the action defined in the same repository.
        uses: ./
        with:
          config: "tests/config.toml"
          SLACK_AUTH_TOKEN: ${{ secrets.SLACK_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ORG: ${{ secrets.GITHUB_ORG }}
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
